name: Manual job

on:
  workflow_dispatch:

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo ${GITHUB_REF_NAME}
  
  run_tests:
    needs: is_deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests
