name: Astronomer CI - Create and then deploy a preview environment

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  create_and_deploy:
    if: github.event.comment.body == '/create' && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "$BODY"

  run_airflow_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests

  deploy_to_preview:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Deployment Preview
      run: echo deploying