name: Astronomer CI - Create and then deploy a preview environment

on:
  issue_comment:
    types: [created]

jobs:
  is_create:
    if: ${{ github.event.comment.body == '/create' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: echo Creating deployment

  is_deploy:
    if: ${{ github.event.comment.body == '/deploy' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: echo Deploying to preview

  create_deployment:
    needs: is_create
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo ${GITHUB_REF_NAME}
  
  run_airflow_tests:
    needs: is_deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests

  deploy_to_preview:
    needs: run_airflow_tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Deployment Preview
      run: echo deploying
