name: Manual job

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of your branch"
        default: ""

jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      run: echo ${{ github.event.inputs.branch_name }}
  
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests
