name: Astronomer CI - Create Deployment Preview

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  create_deployment_preview:
    if: github.event.comment.body == '/create' && contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "$BODY"
