name: Manual job

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of your branch"
        default: ""

env:
  MY_VAR: hello

jobs:
  create_deployment:
    if: ${{ github.event.inputs.branch_name != '' }}
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      run: echo ${{ github.event.inputs.branch_name }}_$MY_VAR
  
  run_tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch_name != '' }}
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests $MY_VAR
