name: Astronomer CI - Create and then deploy a preview environment

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Check if deployment already exists
      id: deployment_check
      runs-on: ubuntu-latest
      run: echo ${{ steps.extract_branch.outputs.branch }}

  create_deployment:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "$BODY"
  
  run_airflow_tests:
    needs: create_deployment
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests

  deploy_to_preview:
    needs: run_airflow_tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Deployment Preview
      run: echo deploying
