name: Astronomer CI - Create and then deploy a preview environment

on:
  pull_request:
    types: ['opened', 'ready_for_review']
    branches:
      - main

jobs:
  create_deployment:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "$BODY"
  
  run_airflow_tests:
    needs: create_deployment
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: Auto-pytest
      run: echo running some tests

  deploy_to_preview:
    needs: run_airflow_tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Deployment Preview
      run: echo deploying
